!
hostname bgpd
password zebra
enable password zebra
!
router bgp 1
network 1.2.0.0/30
network 11.0.0.28/30
!
neighbor 11.0.0.30 remote-as 30
neighbor 11.0.0.30 description Router as30r1 (backup link)
neighbor 11.0.0.30 default-originate route-map backupMetric
neighbor 11.0.0.30 prefix-list acceptAny in
neighbor 11.0.0.30 prefix-list defaultOut out
!
ip prefix-list acceptAny permit any
ip prefix-list defaultOut permit 0.0.0.0/0
!
route-map backupMetric permit 10
set metric 100
!
log file /var/log/quagga/bgpd.log
!
debug bgp
debug bgp events
debug bgp filters
debug bgp fsm
debug bgp keepalives
debug bgp updates
!