!
! FRRouting configuration file
!
!
!    BGP CONFIGURATION
!
!
router bgp 200
no bgp ebgp-requires-policy
no bgp network import-check
network 60.0.0.0/16
neighbor 150.0.0.1 remote-as 10
neighbor 150.0.0.1 description bb4
!
log file /var/log/frr/frr.log