!
hostname bgpd
password zebra
enable password zebra
!
router bgp 1
network 1.3.0.0/30
network 1.4.0.0/30
!
neighbor 1.4.0.2 remote-as 400
neighbor 1.4.0.2 description Router as400r1
neighbor 1.4.0.2 default-originate
neighbor 1.4.0.2 prefix-list acceptAny in
neighbor 1.4.0.2 prefix-list defaultOut out
!
ip prefix-list acceptAny permit any
ip prefix-list defaultOut permit 0.0.0.0/0
!
log file /var/log/quagga/bgpd.log
!
debug bgp
debug bgp events
debug bgp filters
debug bgp fsm
debug bgp keepalives
debug bgp updates
!