!
hostname bgpd
password zebra
enable password zebra
!
router bgp 400
network 40.40.0.0/16
!
neighbor 1.4.0.1 remote-as 1
neighbor 1.4.0.1 description Router as1r3
neighbor 1.4.0.1 prefix-list acceptAny in
neighbor 1.4.0.1 prefix-list mineOnly out
!
ip prefix-list acceptAny permit any
ip prefix-list mineOnly permit 40.40.0.0/16
!
log file /var/log/quagga/bgpd.log
!
debug bgp
debug bgp events
debug bgp filters
debug bgp fsm
debug bgp keepalives
debug bgp updates
!