!
! FRRouting configuration file
!
!
!    OSPF CONFIGURATION
!
router ospf
network 10.0.0.0/16 area 0.0.0.0
redistribute connected
redistribute bgp
!
!    BGP CONFIGURATION
!
router bgp 10
no bgp ebgp-requires-policy
no bgp network import-check
network 10.0.0.0/16
neighbor 150.0.0.2 remote-as 200
neighbor 150.0.0.2 description as200r1
!
log file /var/log/frr/frr.log